[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "php83Extensions.mbstring", "php83Extensions.curl"]

[phases.build]
cmds = ["php -m"]

[deploy]
cmd = "mysql -h $MYSQLHOST -P $MYSQLPORT -u $MYSQLUSER -p$MYSQLPASSWORD $MYSQLDATABASE < database/setup.sql && php database/seed.php && php -S 0.0.0.0:$PORT -t ."
